config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :boards
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
class Board < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :set_target_board, only: %i[show edit update destroy]
  def index
    # kaminariの使用。pageメソッドを呼ぶことにより、引数に指定したページに表示するデータだけを取得。デフォルトでは、1ページ辺り25件のデータを取得する
    @boards = Board.page(params[:page])
  end
  def new
    @board = Board.new
  end
  def create
    board = Board.create(board_params)
    flash[:notice] = "「#{board.title}」の掲示板を作成しました"
    # 特定のモデルの詳細画面にリダイレクトする場合はリダイレクトというメソッドの引数にオブジェクトを指定するだけで転送してくれる。パスを指定しても良い
    redirect_to board
  end
  def show
  end
  def edit
  end
  def update
    # インスタンス変数ではなく、ローカル変数に代入。今回のupdateアクションでは、viewに表示する必要がないから
    # updateメソッドで行う引数にはハッシュ形式でプロパティイ名と値の組を渡す
    @board.update(board_params)
    # 特定のモデルの詳細画面にリダイレクトする場合はリダイレクトというメソッドの引数にオブジェクトを指定するだけで転送してくれる。パスを指定しても良い
    redirect_to @board
  end
  def destroy
    @board.delete
    redirect_to boards_path, flash: {notice: "「#{@board.title}」の掲示板を作成しました"}
  end


  # ストロングパラメーター。意図していないparamsが渡ってくるのを防ぐ。フィルターをかけている
  private
  def board_params
    # paramsの中にある、boardキーのname,title,bodyの値のみ受け取る
    params.require(:board).permit(:name, :title, :body)
  end
  def set_target_board
    @board = Board.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/boards/_board.html.erb
<div class="card">
  <div class="card-header">
    <h4><%= board.title %></h4>
  </div>
  <div class="card-body">
    <p class="card-text"><%= simple_format(@board.body) %></p>
    <p class="text-right font-weight-bold mr-10"><%= @board.name %></p>
  </div>
</div>

app/views/boards/_form.html.erb
<%# bordモデルのデータを新規に作成するフォームを作ることができる。methodはpostに自動でなる。 %>
<%# Rails5.1以降はform_forやform_tag使わずにform_withらしい。今回はRails5.0.1なのでform_for%>
<%# new.html.erb及びedit.html.erbからローカル変数boardが渡されている %>
<%= form_for board do |f| %>
  <div class="form-group">
    <%= f.label :name, '名前' %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :title, 'タイトル' %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :body, '本文' %>
    <%= f.text_area :body, class: 'form-control', rows: 10 %>
  </div>
  <%= f.submit '保存', class: 'btn btn-primary' %>
<% end %>

app/views/boards/edit.html.erb
<div class="d-flex align-items-center">
  <h1>掲示板編集</h1>
  <div class="ml-auto boards__linkBox">
    <%= link_to '一覧', boards_path, class: 'btn btn-outline-dark'  %>
  </div>
</div>
<%# パーシャルを呼び出す場合はレンダーメソッドを使い、その後ろにハッシュ形式で呼び出すパーシャル名を指定。 %>
<%# locals以下の記載について。これがあることで、edit.html.erbをみた時に@boardというインスタンス変数が使われていることが確認でき、パーシャル側にはboardというローカル変数が渡ることになる %>
<%= render partial: 'form', locals: { board: @board } %>

app/views/boards/index.html.erb
<div class="d-flex align-items-center">
  <h1>掲示板一覧</h1>
  <div class="ml-auto boards__linkBox">
    <%= link_to '新規作成', new_board_path, class: 'btn btn-outline-dark'  %>
  </div>
</div>
<% if flash[:notice] %>
  <div class="alert alert-danger"><%= flash[:notice] %></div>
<% end %>
<table class="table table-hover boards__table">
  <thead class="thead-dark">
    <tr>
      <th>ID</th>
      <th>タイトル</th>
      <th>作成者</th>
      <th>作成日時</th>
      <th>更新日時</th>
    </tr>
  </thead>
  <tbody>
  <% @boards.each do |board| %>
    <tr>
      <td><%= board.id %></td>
      <td><%= board.title %></td>
      <td><%= board.name %></td>
      <td><%= board.created_at.to_s(:datetime_jp) %></td>
      <td><%= board.updated_at.to_s(:datetime_jp) %></td>
      <%# link_toの第二引数にオブジェクトを指定することで、そのオブジェクトの詳細画面へ遷移できる %>
      <td><%= link_to '詳細', board, class: 'btn btn-outline-dark' %></td>
      <td><%= link_to '削除', board, class: 'btn btn-outline-dark', method: :delete %></td>
    </tr>
  <% end %>
    <tr>
      <th>2</th>
      <td>雑談掲示板2</td>
      <td>Ken</td>
      <td>2018年4月1日</td>
      <td>2018年4月15日</td>
    </tr>
  </tbody>
</table>
<%# kaminariによってpaginateヘルパーが使用できるようになる %>
<%= paginate @boards %>

app/views/boards/new.html.erb
<div class="d-flex align-items-center">
  <h1>掲示板作成</h1>
  <div class="ml-auto boards__linkBox">
    <%= link_to '一覧', boards_path, class: 'btn btn-outline-dark'  %>
  </div>
</div>
<%# パーシャルを呼び出す場合はレンダーメソッドを使い、その後ろにハッシュ形式で呼び出すパーシャル名を指定。 %>
<%# locals以下の記載について。これがあることで、new.html.erbをみた時に@boardというインスタンス変数が使われていることが確認でき、パーシャル側にはboardというローカル変数が渡ることになる %>
<%= render partial: 'form', locals: { board: @board } %>

app/views/boards/show.html.erb
<div class="d-flex align-items-center mt-4 mb-4">
  <div class="ml-auto boards__linkBox">
    <%= link_to '一覧', boards_path, class: 'btn btn-outline-dark'  %>
    <%# 編集対象のモデルオブジェクトを引数に渡す %>
    <%= link_to '編集', edit_board_path(@board), class: 'btn btn-outline-dark' %>
  </div>
</div>
<%# フラッシュメッセージの表示 %>
<% if flash[:notice] %>
  <div class="alert alert-primary"><%= flash[:notice] %></div>
<% end %>
<%# オブジェクトというキーに関して、変数を渡した場合はアンダースコアを抜いた変数名が作成されて、パーシャルで参照できるようになる %>
<%# <%= render partial: 'board', locals: { board: @board } %> 
<%= render partial: 'board', object: @board %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="container">
    <%= yield %>
  </div>
  </body>
</html>